### ISSUE TITLE
Prod9 ansible issues

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#671]
Got told here there were issues, 
http://drunkardswalkforums.yuku.com/reply/131176/All-The-Tropes-Wiki-Project-Part-V#reply-131176

Did an ansible update/LC refresh, prod9 seems to have issues updating:

failed: [prod9] => {"failed": true, "parsed": false}
SUDO-SUCCESS-ksmdtqjzgqneueipgcwbmuzshwxhrugh
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1437238957.13-66973874499702/git", line 2464, in <module>
    main()
  File "/tmp/ansible-tmp-1437238957.13-66973874499702/git", line 590, in main
    supports_check_mode=True
  File "/tmp/ansible-tmp-1437238957.13-66973874499702/git", line 1033, in __init__
    self._set_cwd()
  File "/tmp/ansible-tmp-1437238957.13-66973874499702/git", line 1850, in _set_cwd
    for cwd in [os.path.expandvars('$HOME'), tempfile.gettempdir()]:
  File "/usr/lib/python2.7/tempfile.py", line 269, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 212, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root/ansible-playbook']

Seems prod9 is having trouble syncing to the WMF servers for updates.

**Comment by Reception123** [comment]
All wikis (except meta) are down - 404 Not Found -

**Comment by Reception123** [comment]
DISK CRITICAL - free space: / 0 MB (0% inode=81%): 
I found this on nagios.orain.org

**Comment by addshore** [comment]
Resolved
